on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

     - uses: actions/checkout@v3

     - name: "login to doker hup"
       run: docker login --username eslamcoder77 --password docker login -u eslamcoder77


   
      

            