on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    

     - name: "login to docker hup"
       run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} 


      - name: "building docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage .

      - name: "pushing to docker hup"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage 


        - name: "test"
          run: echo eslam


   
      

            